### ISSUE TITLE
Include ability to spread deidentification over multiple nodes in a batch pool

### ISSUE THREAD

**Issue by theGOTOguy** [microsoft/Tools-for-Health-Data-Anonymization#172]
Currently, the ADF pipeline is only able to execute on a single node, though that node can be of arbitrary size.

It takes us more than 48 hours to deidentify our entire set of FHIR resources.  Since the task of deidentification is embarrassingly parallel, we would like the ability to spread our processing out over more than a single node so that we can deidentify our resources more quickly.

**Comment by irenepjoseph** [comment]
@theGOTOguy, what is the data volume of FHIR resources that you were using?

**Comment by theGOTOguy** [comment]
Currently we have approximately 2.6 million FHIR records, but we have plans to scale up.
