### ISSUE TITLE
Complete fhirPathRules example

### ISSUE THREAD

**Issue by bwalsh** [microsoft/Tools-for-Health-Data-Anonymization#185]
Thanks for a great product.
Is there a more complete example of redacting FHIR bundles?
  For example:
   * shift all date fields and ages
   * redact all identifiers

**Comment by sowu880** [comment]
Hi @bwalsh,
 You can use "nodesByType" in configuration, here are examples:
https://github.com/microsoft/Tools-for-Health-Data-Anonymization/blob/master/FHIR/src/Microsoft.Health.Fhir.Anonymizer.Stu3.CommandLineTool/configuration-sample.json#L154
