### ISSUE TITLE
Filename too long

### ISSUE THREAD

**Issue by TerriblyVexed** [microsoft/Tools-for-Health-Data-Anonymization#211]
error: unable to create file FHIR/src/Microsoft.Health.Fhir.Anonymizer.R4.AzureDataFactoryPipeline.UnitTests/Microsoft.Health.Fhir.Anonymizer.R4.AzureDataFactoryPipeline.UnitTests.csproj: Filename too long
error: unable to create file FHIR/src/Microsoft.Health.Fhir.Anonymizer.Shared.AzureDataFactoryPipeline.UnitTests/Microsoft.Health.Fhir.Anonymizer.Shared.AzureDataFactoryPipeline.UnitTests.projitems: Filename too long
error: unable to create file FHIR/src/Microsoft.Health.Fhir.Anonymizer.Shared.AzureDataFactoryPipeline.UnitTests/Microsoft.Health.Fhir.Anonymizer.Shared.AzureDataFactoryPipeline.UnitTests.shproj: Filename too long
error: unable to create file FHIR/src/Microsoft.Health.Fhir.Anonymizer.Stu3.AzureDataFactoryPipeline.UnitTests/Microsoft.Health.Fhir.Anonymizer.Stu3.AzureDataFactoryPipeline.UnitTests.csproj: Filename too long
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.

**Comment by mikesoennichsen** [comment]
Hello, could you provide some more information on where this issue occurred including steps to reproduce and any other relevant information like environment and OS. Have you looked into the following git config: `git config --system core.longpaths true`

**Comment by jovinson-ms** [comment]
Feel free to re-open!
