### ISSUE TITLE
configuration.json in CommandLineTool doesn't parse because of {"tag":"(50xx,xxxx)", "method":"remove"}

### ISSUE THREAD

**Issue by TD-peter** [microsoft/Tools-for-Health-Data-Anonymization#220]
Number.Parsing throws an exception: System.FormatException: 'The input string '50xx' was not in a correct format.' when trying to parse the configuration.json file in the project. The offending line is:

        {"tag":"(50xx,xxxx)", "method":"remove"}, 
        {"tag":"(60xx,4000)", "method":"remove"}, 
        {"tag":"(60xx,3000)", "method":"remove"}, 

The (50xx,xxxx) etc. values are obviously not valid. 

Also:
        {"tag":"DA", "method":"dateshift"},
        {"tag":"DT", "method":"dateshift"}

Do not parse.

Please remove or update this line. Location of the file:
DICOM/src/Microsoft.Health.Dicom.Anonymizer.CommandLineTool/configuration.json

**Comment by alexathomases** [comment]
Thank you so much for raising this issue. Our team is looking into it and will provide you an update as soon as possible.

**Comment by alexathomases** [comment]
Hi @TD-peter, can you please provide the steps to reproduce this issue? I have not been able to reproduce while using the command `.\Microsoft.Health.Dicom.Anonymizer.CommandLineTool.exe -i myInputFile -o myOutputFile` from the $SOURCE\DICOM\src\Microsoft.Health.Dicom.Anonymizer.CommandLineTool\bin\Debug|Release\net6.0 folder.

**Comment by TD-peter** [comment]
Hi Alexa, sorry for my late reply. Perhaps the input files you used did not contain any tags in the ranges I mentioned. The problem is that xx is not a valid value, it is a placeholder for any hex value. Valid values are in the hex range (so ff is the maximum value that is allowed).

Either the code should recognize xx as a wildcard, or the wildcards in the .json file should be expanded to a range of valid values.

Also, I noticed that the tag (3008,0105) is listed twice in the .json file:

        {"tag":"(3008,0105)", "method":"remove"}, 
        {"tag":"(3008,0105)", "method":"remove"}, 

Thank you!

**Comment by TD-peter** [comment]
![image](https://github.com/microsoft/Tools-for-Health-Data-Anonymization/assets/123555892/b65715b6-037f-418d-8f57-75dd0c438981)

**Comment by TD-peter** [comment]
So my question is: what would be the most efficient way to make sure that all tags that match with the wildcard pattern are processed according to the rule? For example:
{"tag":"(50xx,xxxx)", "method":"remove"}, 
Should apply to ALL tags from (5000,0000) all the way to (50FF,FFFF). To create a rule for each of these values would be very inefficient. So what can we do to make sure that we can keep the wildcard pattern in the tag and create a Anonymizer rule that can handle wildcards? The current TryCreateRule method in AnonymizerRuleFactory will fail, because it is trying to call the Parse method on a FellowOakDicom.DicomTag object, which expects the value to be a hexadecimal value, so it can't include any xx.

**Comment by TD-peter** [comment]
Duplicate tag has been removed in #222 . Parse exception is expected behavior, so this bug can be closed.
