### ISSUE TITLE
Consider allowing comments in configuration files

### ISSUE THREAD

**Issue by mikix** [microsoft/Tools-for-Health-Data-Anonymization#221]
When writing a configuration file, it is extremely useful to comment _why_ a line was added (or often more importantly, why a line is _not_ present).

JSON doesn't support comments. So what I've done for my config files is to add a `comment` field like so:
```json
{"path": "Immunization.lotNumber", "method": "keep", "comment": "this is useful for X reason"},
```

Or more awkwardly, when I want to explain why a line _isn't_ there or want to demark a section of rules:
```json
{"comment": "** https://www.hl7.org/fhir/R4/immunization.html **", "path": "xxx", "method": "redact"},
{"comment": "Immunization.lotNumber isn't useful for Y reason", "path": "xxx", "method": "redact"},
```

But life would be a lot easier if I could just use comments - and would be more performant because the tool doesn't need to apply these fake rules.

**YAML Option**
JSON is ([mostly](https://john-millikin.com/json-is-not-a-yaml-subset)) a subset of YAML - i.e. a YAML parser can read JSON. So by switching your config parser to a YAML parser, you'd lose no functionality and folks that wanted to use YAML (which supports comments) could.

**JSON Option**
Use a JSON parser that extends the format to allow for comments, or preprocess the config file to remove comments or some such workaround.

**Comment by mikix** [comment]
I suppose alternatively, use a JSON parser that extends the format to allow for comments, or preprocess the config file to remove comments or some such workaround.

I don't care about YAML so much as I care about being able to have comments.

**Comment by jovinson-ms** [comment]
Hi @mikix, can you provide a toy sample configuration file that you'd like to see? On first glance, the code should follow Newtonsoft's default behavior of ignoring comments when parsing the configuration file.

**Comment by mikix** [comment]
OK I'm a crazy person, I'm learning. I could have sworn I actually tested comments.

But doing so now, indeed C-style comments like `/* hello */` and `// hello` are both allowed. Which solves my problem entirely.

It might be nice to nudge other people towards that same realization by using that syntax in the [docs](https://github.com/microsoft/Tools-for-Health-Data-Anonymization/blob/master/docs/FHIR-anonymization.md) or the [sample config](https://github.com/microsoft/Tools-for-Health-Data-Anonymization/blob/master/FHIR/src/Microsoft.Health.Fhir.Anonymizer.R4.CommandLineTool/configuration-sample.json). Other folks like me might not expect that behavior, because normally JSON does not allow it. But that's a much lower priority than supporting comments in the first place, which is already done.

Thank you! I'll close this issue.
