### ISSUE TITLE
Explicit offset for date-shift for FHIR resources

### ISSUE THREAD

**Issue by mrunibe** [microsoft/Tools-for-Health-Data-Anonymization#225]
The offset (number of days) for the date-shift is currently derived randomly from a hash.

However, we have a use-case where we would need to explicitly provide this offset for the date-shift externally (the value is coming from another component/tool).

Therefore, it would be helpful to have such an option, for example by extending the parameters for the date-shift by:
	"_dateShiftFixedOffset_" [integer]

If present, fields with the method "_dateShift_" would be shifted by this fixed amount of "_dateShiftFixedOffset_".

Or is there another possibility to achieve this?

**Comment by alexathomases** [comment]
Thank you for your suggestion. We have work in-progress to enable this functionality.

Our current design proposes that "_dateShiftFixedOffset_" will have a unit of days and, if present, will apply to all fields in the resource. Please let us know if this will suit your use-case.

**Comment by alexathomases** [comment]
I have created [this pull request](https://github.com/microsoft/Tools-for-Health-Data-Anonymization/pull/227) to enable the functionality you requested.

**Comment by mrunibe** [comment]
> I have created [this pull request](https://github.com/microsoft/Tools-for-Health-Data-Anonymization/pull/227) to enable the functionality you requested.

Hi Alexa,

I have successfully tested it and it works exactly as desired. Thanks for this feature!

**Comment by alexathomases** [comment]
> > I have created [this pull request](https://github.com/microsoft/Tools-for-Health-Data-Anonymization/pull/227) to enable the functionality you requested.
> 
> Hi Alexa,
> 
> I have successfully tested it and it works exactly as desired. Thanks for this feature!

The PR has been merged.

**Comment by alexathomases** [comment]
Closing this issue as feature request has been delivered.
